export const branches = [
  {
    id: "market",
    slug: "markets",
    name: "فرع الأسواق المركزية والمطاعم",
    description:
      "يُعد فرع الأسواق المركزية زهابكو من الفروع العريقة بمجموعة شركات الظاهري بل أحد أقدم الشركات في المملكة العربية السعودية، حيث تأسست في الثمانينات...",
    mainImage: "/2024-Oct-Tue_6705083a1d342.png",
    audio: "/branches/market/intro.mp3",
    vision: [
      "أن نكون قدوة في المسؤولية الاجتماعية ودعم المجتمع المحلي.",
      "الالتزام بأعلى معايير الجودة والسلامة.",
      "أن نكون الخيار الأول في المنطقة.",
    ],
    mission: [
      "تقديم تجربة تسوق متميزة لعملائنا.",
      "توفير منتجات عالية الجودة بأسعار مناسبة.",
    ],
    goals: [
      "التوسع في عدد الفروع.",
      "تحسين تجربة العملاء.",
      "دعم المنتجات الوطنية.",
    ],
    values: ["الجودة", "المصداقية", "العمل الجماعي", "الابتكار"],
    gallery: [
      "/ceo.png",
      "/ceo-about.png",
      "/s2.jpg",
      "/s3.jpg",
      "/s5.jpg",
      "/s4.jpg",
    ],
    videos: ["/branches/market/1.mp4", "/branches/market/2.mp4"],
    path: "/branche?branch=markets",
  },
  {
    id: "food",
    slug: "food",
    name: "فرع المواد الغذائية والإعاشة",
    description:
      "يعد فرع الإعاشة والتشغيل من الركائز الأساسية لمجموعة شركات الظاهري منذ تأسيسها عام ١٩٨٣م، ويتمتع بخبرة واسعة وسمعة مرموقة في السوق السعودي والخليجي...",
    mainImage: "/branches/food/main.jpg",
    audio: "/branches/food/intro.mp3",
    vision: [
      "أن نكون قدوة في المسؤولية الاجتماعية ودعم المجتمع المحلي.",
      "الالتزام بأعلى معايير الجودة والسلامة.",
      "أن نكون الخيار الأول في المنطقة.",
    ],
    mission: [
      "تقديم تجربة تسوق متميزة لعملائنا.",
      "توفير منتجات عالية الجودة بأسعار مناسبة.",
    ],
    goals: [
      "التوسع في عدد الفروع.",
      "تحسين تجربة العملاء.",
      "دعم المنتجات الوطنية.",
    ],
    values: ["الجودة", "المصداقية", "العمل الجماعي", "الابتكار"],
    gallery: ["/branches/food/1.jpg", "/branches/food/2.jpg"],
    videos: [],
    path: "/branche?branch=food",
  },
  {
    id: "kitchens",
    slug: "kitchens",
    name: "وجار الخليج لمعدات المطابخ",
    description: "وصف مختصر عن وجار الخليج لمعدات المطابخ...",
    mainImage: "/branches/kitchens/main.jpg",
    audio: "/branches/kitchens/intro.mp3",
    vision: [],
    mission: [],
    goals: [],
    values: [],
    gallery: [],
    videos: [],
    path: "/branche?branch=kitchens",
  },
  {
    id: "contracting",
    slug: "contracting",
    name: "فرع المقاولات العامة",
    description: "وصف مختصر عن فرع المقاولات العامة...",
    mainImage: "/branches/contracting/main.jpg",
    audio: "/branches/contracting/intro.mp3",
    vision: [],
    mission: [],
    goals: [],
    values: [],
    gallery: [],
    videos: [],
    path: "/branche?branch=contracting",
  },
  {
    id: "security",
    slug: "security",
    name: "فرع القعقاع للخدمات الأمنية",
    description: "وصف مختصر عن فرع القعقاع للخدمات الأمنية...",
    mainImage: "/branches/security/main.jpg",
    audio: "/branches/security/intro.mp3",
    vision: [],
    mission: [],
    goals: [],
    values: [],
    gallery: [],
    videos: [],
    path: "/branche?branch=security",
  },
  {
    id: "trading",
    slug: "trading",
    name: "فرع العمليات التجارية والتوكيلات",
    description: "وصف مختصر عن فرع العمليات التجارية والتوكيلات...",
    mainImage: "/branches/trading/main.jpg",
    audio: "/branches/trading/intro.mp3",
    vision: [],
    mission: [],
    goals: [],
    values: [],
    gallery: [],
    videos: [],
    path: "/branche/trading",
  },
  {
    id: "uae",
    slug: "uae",
    name: "فرع الإمارات",
    description: "وصف مختصر عن فرع الإمارات...",
    mainImage: "/branches/uae/main.jpg",
    audio: "/branches/uae/intro.mp3",
    vision: [],
    mission: [],
    goals: [],
    values: [],
    gallery: [],
    videos: [],
    path: "/branches/uae",
  },
  {
    id: "military",
    slug: "military",
    name: "فرع التجهيزات العسكرية والأمنية",
    description: "وصف مختصر عن فرع التجهيزات العسكرية والأمنية...",
    mainImage: "/branches/military/main.jpg",
    audio: "/branches/military/intro.mp3",
    vision: [],
    mission: [],
    goals: [],
    values: [],
    gallery: [],
    videos: [],
    path: "/branche/military",
  },
];
